// playground/client/pages/index.jsx
export default function Index() {
  const message = 'Welcome to @fastify/react!';
  return (
    <>
      <p>{message}</p>

      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi quasi a
        atque numquam error vero inventore alias at ad officia incidunt quia
        suscipit reprehenderit dicta, nisi quibusdam odio? Earum, enim!
      </p>
    </>
  );
}

// playground/app/pages/index.vue
<script lang="ts" setup>
useTestComposable();
</script>

<template>
  <SubUseTest />
  Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt asperiores
  error perferendis cupiditate. Quae est eos vero nisi doloribus, enim fugit
  praesentium! Sunt dolore debitis, autem rerum in fugiat nisi.
</template>
